services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
    redis:
        image: redis:latest
        ports:
            - 6379:6379
    