export const endpoints = {
    baseUrl: "http://localhost:7001/api/v1",
    courses: "/course",
    users: "/user",
    comments: "/comment",
    login: "/login",
    courseDetail: "/course",
    userDetails: "/user/profile",
    cart:"/cart",
    checkIfBought: "/course/checkifbought",
    payment: "/payment",
    myLearning: "/user/profile/course",
    signup: "/login/register",
    category: '/course/category',
    getAllCategory: '/course/categories',
    getAccessToken: '/login/GetAccessToken',
    teacherCourse: "/user/teacher/courses",
    paymentHistory: "/user/payment-history",
};